# -*- coding: utf-8 -*-
"""Copia de entrenar_deteccion_huevos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mcKmB7PzNdBc17YB_Tgs_0QwS1p6fceF

# Entrenar modelo de detección de huevos (YOLOv8-seg)

Antes de correr nada: en el menú de arriba ve a **Entorno de ejecución → Cambiar tipo de entorno de ejecución** y selecciona **GPU (T4)**. Sin eso, el entrenamiento va a ser muy lento.
"""

# 1) Instalar librerías necesarias
!pip install roboflow ultralytics -q

# 2) Descargar el dataset desde Roboflow (formato COCO Segmentation)
# Pega aquí el snippet que copiaste de Roboflow (reemplaza esto con el tuyo,
# especialmente tu api_key, que es privada de tu cuenta):

from roboflow import Roboflow
rf = Roboflow(api_key="EMts0Q9i5SNt11mHYODK")
project = rf.workspace("sofia-bolanos").project("deteccion-huevos")
version = project.version(1)
dataset = version.download("coco-segmentation")

print("Dataset descargado en:", dataset.location)

# 3) Convertir de formato COCO Segmentation al formato YOLOv8-seg
# (maneja tanto polígonos normales como máscaras RLE, que es lo que
#  genera el auto-labeling con SAM 3 en Roboflow)

!pip install pycocotools -q

import json
import os
import shutil
import numpy as np
import cv2
from pycocotools import mask as maskUtils

DATASET_DIR = dataset.location
SPLITS = ["train", "valid", "test"]

def poligono_desde_rle(rle, alto, ancho):
    """Convierte una máscara RLE (píxeles) en un contorno (lista de puntos x,y)."""
    if isinstance(rle["counts"], list):
        rle = maskUtils.frPyObjects(rle, alto, ancho)
    mascara = maskUtils.decode(rle)
    contornos, _ = cv2.findContours(mascara.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contornos:
        return None
    contorno_mas_grande = max(contornos, key=cv2.contourArea)
    return contorno_mas_grande.reshape(-1, 2).flatten().tolist()

def convertir_split_coco_a_yolo(split):
    carpeta_split = os.path.join(DATASET_DIR, split)
    ruta_json = os.path.join(carpeta_split, "_annotations.coco.json")
    if not os.path.exists(ruta_json):
        print(f"Aviso: no se encontró {ruta_json}, se omite el split '{split}'")
        return None

    with open(ruta_json, "r") as f:
        coco = json.load(f)

    imagenes = {img["id"]: img for img in coco["images"]}
    categorias = {cat["id"]: i for i, cat in enumerate(coco["categories"])}

    carpeta_labels = os.path.join(carpeta_split, "labels")
    os.makedirs(carpeta_labels, exist_ok=True)

    anotaciones_por_imagen = {}
    for ann in coco["annotations"]:
        anotaciones_por_imagen.setdefault(ann["image_id"], []).append(ann)

    contador = 0
    total_instancias = 0
    for id_img, info_img in imagenes.items():
        ancho = info_img["width"]
        alto = info_img["height"]
        nombre_base = os.path.splitext(info_img["file_name"])[0]
        ruta_txt = os.path.join(carpeta_labels, nombre_base + ".txt")

        lineas = []
        for ann in anotaciones_por_imagen.get(id_img, []):
            clase = categorias[ann["category_id"]]
            segmentacion = ann.get("segmentation", [])

            puntos_planos = None
            if isinstance(segmentacion, dict):
                # formato RLE (máscara de píxeles) -> convertir a contorno
                puntos_planos = poligono_desde_rle(segmentacion, alto, ancho)
            elif isinstance(segmentacion, list) and len(segmentacion) > 0:
                # formato polígono normal (ya es una lista de puntos)
                puntos_planos = segmentacion[0]

            if not puntos_planos or len(puntos_planos) < 6:
                continue

            coords_norm = []
            for i in range(0, len(puntos_planos), 2):
                x = puntos_planos[i] / ancho
                y = puntos_planos[i + 1] / alto
                coords_norm.extend([round(x, 6), round(y, 6)])
            lineas.append(f"{clase} " + " ".join(str(c) for c in coords_norm))
            total_instancias += 1

        with open(ruta_txt, "w") as f_out:
            f_out.write("\n".join(lineas))

        contador += 1

    print(f"{split}: {contador} imágenes procesadas, {total_instancias} huevos etiquetados")
    return contador, categorias

nombres_clases = None
for split in SPLITS:
    resultado = convertir_split_coco_a_yolo(split)
    if resultado:
        n, categorias = resultado
        if nombres_clases is None:
            with open(os.path.join(DATASET_DIR, split, "_annotations.coco.json")) as f:
                cats_json = json.load(f)["categories"]
            nombres_clases = [None] * len(cats_json)
            for cat in cats_json:
                nombres_clases[categorias[cat["id"]]] = cat["name"]

print("Clases detectadas:", nombres_clases)



# 4) Crear el archivo data.yaml que necesita YOLOv8 para entrenar
import os
import shutil

for split in SPLITS:
    carpeta_split = os.path.join(DATASET_DIR, split)
    if not os.path.isdir(carpeta_split):
        continue
    carpeta_images = os.path.join(carpeta_split, "images")
    os.makedirs(carpeta_images, exist_ok=True)

    extensiones = (".jpg", ".jpeg", ".png")
    for nombre_archivo in os.listdir(carpeta_split):
        ruta_origen = os.path.join(carpeta_split, nombre_archivo)
        if os.path.isfile(ruta_origen) and nombre_archivo.lower().endswith(extensiones):
            shutil.move(ruta_origen, os.path.join(carpeta_images, nombre_archivo))

    print(f"{split}: fotos movidas a {carpeta_images}")

yaml_contenido = f"""
train: {DATASET_DIR}/train/images
val: {DATASET_DIR}/valid/images
test: {DATASET_DIR}/test/images

nc: {len(nombres_clases)}
names: {nombres_clases}
"""

ruta_yaml = os.path.join(DATASET_DIR, "data.yaml")
with open(ruta_yaml, "w") as f:
    f.write(yaml_contenido)

print("data.yaml creado en:", ruta_yaml)
print(yaml_contenido)





# 5) Entrenar el modelo YOLOv8-seg (versión 'nano', la más liviana y rápida,
#    ideal para correr después en tu PC sin GPU dedicada)

from ultralytics import YOLO

modelo = YOLO("yolov8n-seg.pt")  # pesos pre-entrenados como punto de partida

resultados = modelo.train(
    data=ruta_yaml,
    epochs=80,
    imgsz=640,
    batch=16,
    name="deteccion_huevos"
)

# 6) Descargar el modelo entrenado (best.pt) a tu computador

from google.colab import files

ruta_best = "runs/segment/deteccion_huevos/weights/best.pt"
files.download(ruta_best)

"""## Siguiente paso

Cuando termine de descargarse `best.pt`, guárdalo dentro de tu carpeta `deteccion-huevos` en tu PC (por ejemplo en una subcarpeta `modelo/`). Ese archivo es el que va a cargar tu `server.py` con FastAPI, igual que `digit_model.pth` en tu otro proyecto.
"""